version: '3.8'

services:
  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_test
    ports:
      - "8501:8501"
    volumes:
      - ./csv:/app/csv
      - ./images:/app/images
    restart: unless-stopped

  control-app:
    build:
      context: .
      dockerfile: Dockerfile.control
    container_name: app_control
    ports:
      - "8502:8502"
    volumes:
      - ./csv:/app/csv
      - ./images:/app/images
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped